name: "SBOM"
description: "sbom"


inputs:
  version:
    description: version
    required: true
  release_type: 
    description: release_type
    required: false

runs:
  using: "composite"
  steps:
    - name: call
      uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/container_workflow.yml@v1.43
      with:
        repository_name: ${{github.repository}}
        version: ${{inputs.version}}
        release_type: ${{inputs.release_type}}
        user: ${{ github.actor }}
        team_name: team_test
        organization: Test
