name: S

on:
    workflow_call:
        inputs:
            version:
                type: string

jobs:
    collect-data:
        runs-on: ubuntu-latest
        outputs:
            release_type: ${{ steps.set_release_type.outputs.release_type }}
        steps:
            - name: Set Release Type
              id: set_release_type
              run: |
                BRANCH="${GITHUB_REF##*/}" 
                case "$BRANCH" in
                    master|main)
                    TYPE=production
                    ;;
                    dev|develop)
                    TYPE=development
                    ;;
                    feature/*)
                    TYPE=feature
                    ;;
                    *)
                    TYPE=Manual
                    ;;
                esac
                echo "$TYPE"
                echo "release_type=$TYPE" >> "$GITHUB_OUTPUT"
    send-data:
        needs: [collect-data]
        uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/container_workflow.yml@v1.43
        with:
            repository_name: ${{github.repository}}
            version: ${{inputs.version}}
            release_type: ${{needs.collect-data.outputs.release_type}}
            #checksum_data: ${{needs.collect-data.outputs.checksum_data}}
            user: ${{ github.actor }}
            team_name: team_test
            organization: test
            #input-data: ${{ needs.collect-data.outputs.sbom }}