name: Caller Repo

on:
    workflow_dispatch:

env:
    version: 0.1

jobs:
    collect-data:
        runs-on: ubuntu-latest
        outputs:
            sbom: ${{ steps.set-json.outputs.sbom }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Generate Input JSON
              id: set-json
              run: |
                echo '{"data1": "123", "data2": "456"}' > input.json
                echo "sbom_content=$(cat input.json)" >> $GITHUB_OUTPUT
              shell: bash
    send-data:
        needs: [collect-data]
        uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/api_workflow.yml@master
        with:
            repository_name: ${{ github.repository}}
            user: ${{ github.actor }}
            version: ${{ env.version }}
            input-data: ${{ needs.collect-data.outputs.sbom }}