name: Trigger

on:
    workflow_dispatch:
    push:
        branches:
            fix/update_url
            main

jobs:
  collect-data:
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.set_version.outputs.version }}
        release_type: ${{ steps.set_release_type.outputs.release_type }}
        checksum_data: ${{ steps.build_checksum.outputs.checksum_data }}
        sbom: ${{ steps.generate_sbom.outputs.sbom }}
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        #Install node

        - name: Install Snyk
          run: |
            npm install -g snyk

        - name: Set Release Type
          id: set_release_type
          run: |
            BRANCH="${GITHUB_REF##*/}" 
            case "$BRANCH" in
                master|main)
                echo "RELEASE_TYPE=production" >> "$GITHUB_OUTPUT"
                ;;
                dev|develop)
                echo "RELEASE_TYPE=development" >> "$GITHUB_OUTPUT"
                ;;
                feature/*)
                echo "RELEASE_TYPE=feature" >> "$GITHUB_OUTPUT"
                ;;
                *)
                echo "RELEASE_TYPE=Manual" >> "$GITHUB_OUTPUT"
                ;;
            esac
            echo "release_type=$TYPE" >> "$GITHUB_OUTPUT"

        - name: Set Version
          id: set_version
          run: |
            echo "version=0.0.1" >> $GITHUB_OUTPUT

        - name: sha256 Checksum data
          id: sha256
          run: |
            file_path=./document.pdf
            checksum=$(sha256sum "$file_path" | awk '{print $1}')
            echo "$checksum"
            echo '[{"file_path": "${file_path}", "sha512": "$checksum"}]' > sbom_checksum.json

        - name: sha512 Checksum data
          id: sha512
          run: |
            file_path=./document.pdf
            checksum=$(sha512sum "$file_path" | awk '{print $1}')
            echo "$checksum"
            jq '.+= [{"file_path": "${file_path}", "sha512": "$checksum"}]' sbom_checksum.json > tmp.json && mv tmp.json sbom_checksum.json

        - name: Build checksum array
          id: build_checksum
          run: |
            echo "checksum_data=$(car sbom_checksum.json)" >> GITHUB_OUTPUT
          shell: bash

        - name: Generate Input JSON
          id: generate_sbom
          run: |
              echo "{'user': 'monika', 'data':'12345'}" > input.json
              echo "sbom_content=$(cat input.json)" >> $GITHUB_OUTPUT
          shell: bash
  send-data:
        needs: [collect-data]
        uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/container_workflow.yml@master
        with:
            repository_name: ${{ github.repository }}
            version: ${{needs.collect-data.outputs.version}}
            release_type: ${{needs.collect-data.outputs.release_type}}
            checksum_data: ${{needs.collect-data.outputs.checksum_data}}
            user: ${{ needs.collect-data.outputs.user }}
            team_name: ${{ needs.collect-data.outputs.team_name }}
            organization: ${{ needs.collect-data.outputs.organization}}
            input-data: ${{ needs.collect-data.outputs.sbom }}