on:
    workflow_call:
        inputs:
            enable_sbom:
                type: boolean
                default: false
            enable_v: 
                type: boolean
                default: false
jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "hello" 

            - uses: actions/checkout@v4

            - name: Repo check
              run: echo "${{ github.repository }}"

    sbom_job:
        if: ${{ inputs.enable_sbom }}
        uses: ./.github/workflows/call.yml
    v_job:
        if: ${{ inputs.enable_v }}
        uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/call_v.yaml@master