on:
    workflow_call:
        inputs:
            enable_sbom:
                type: boolean
                default: true
                required: false
            enable_v: 
                type: boolean
                default: false
jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "hello" 

            - uses: actions/checkout@v4

            - name: Repo check
              run: echo "${{ github.repository }}"

            - name: Generate Input JSON
              id: generate_sbom
              run: |
                echo "{\"user\": \"monika\", \"data\":\"12345\"}" > input.json
                encoded_json=$(base64 -w 0 input.json)

            - name: Upload SBOM Artifact
              uses: actions/upload-artifact@v4
              with:
                name: input-json
                path: input.json

            - name: Set Version
              id: set_version
              run: |
                echo "version=0.0.1" >> $GITHUB_OUTPUT

            - name: Set Release Type
              id: set_release_type
              run: |
                BRANCH="${GITHUB_REF##*/}" 
                case "$BRANCH" in
                    master|main)
                    TYPE=production
                    ;;
                    dev|develop)
                    TYPE=development
                    ;;
                    feature/*)
                    TYPE=feature
                    ;;
                    *)
                    TYPE=Manual
                    ;;
                esac
                echo "$TYPE"
                echo "release_type=$TYPE" >> "$GITHUB_OUTPUT"

            - name: Call SBOM
              uses: MonikaSinghal-22/Repo1-action-test/.github/actions/call-sbom@master
              with: 
                version: ${{ steps.set_version.outputs.version }}
                release_type: ${{ steps.set_release_type.outputs.release_type }}

            

    # sbom_job:
    #     if: ${{ inputs.enable_sbom }}
    #     uses: ./.github/workflows/call.yml
    # v_job:
    #     if: ${{ inputs.enable_v }}
    #     uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/call_v.yaml@master