on:
    workflow_call:
        inputs:
            enable_sbom:
                type: boolean
                default: false
            enable_v: 
                type: boolean
                default: false
jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: Test
              run: echo "hello" 

            - uses: actions/checkout@v4

            - name: SBOM
              if: ${{ inputs.enable_sbom }}
              run: echo "enable sbom"

            - name: V
              if: ${{ inputs.enable_v}}
              run: echo "enable v"