on:
    workflow_call:
        inputs:
            enable_sbom:
                type: boolean
                default: true
                required: false
            enable_v: 
                type: boolean
                default: false
jobs:
    checks:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.set_version.outputs.version}}
        steps:
            - name: Test
              run: echo "hello" 

            - uses: actions/checkout@v4

            - name: Repo check
              run: echo "${{ github.repository }}"

            - name: Generate Input JSON
              id: generate_sbom
              run: |
                echo "{\"user\": \"monika\", \"data\":\"12345\"}" > input.json
                encoded_json=$(base64 -w 0 input.json)

            - name: Upload SBOM Artifact
              uses: actions/upload-artifact@v4
              with:
                name: input-json
                path: input.json

            - name: Set Version
              id: set_version
              run: |
                  BRANCH="${GITHUB_REF##*/}"
                  echo "BRANCH= $BRANCH"

                  git fetch --tags --unshallow 2>/dev/null || git fetch --tags

                  version=$(git describe --tags --abbrev=0 2>/dev/null)
                  if [ -z "$version" ]; then 
                    echo "not found"
                  else
                    echo "tag Version $version"
                  fi
                  
                  version=$(git describe --abbrev=0 --match "[0-9]*" 2>/dev/null)
                  if [ -z "$version" ]; then 
                    echo "not found"
                  else
                    echo "tag Version $version"
                  fi
                  
                  version=$(jq -r .version package.json)
                  if [ -z "$version" ]; then 
                    echo "not found"
                  else
                    echo "tag Version $version"
                  fi
              shell: bash

    sbom:
        if: ${{ inputs.enable_sbom }}
        needs: [checks]
        uses: MonikaSinghal-22/Repo1-action-test/.github/workflows/call-sbom.yaml@master
        with: 
            version: ${{ needs.checks.outputs.version }}

            

    # sbom_job:
    #     if: ${{ inputs.enable_sbom }}
    #     uses: ./.github/workflows/call.yml
    # v_job:
    #     if: ${{ inputs.enable_v }}
    #     uses: MonikaSinghal-22/Repo2-action-test/.github/workflows/call_v.yaml@master