name: Trigger Repository 2 Action

on:
  push:
    branches:
      - master  # Runs when code is pushed to 'main'

jobs:
  send-input:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Input JSON
        run: |
            echo '{"user": "monika", "data": "12345"}' > input.json

      - name: Checkout Repository 2
        uses: actions/checkout@v4
        with:
            repository: MonikaSinghal-22/Repo2-action-test  # Repo2's name
            ref: v1.3  # The specific tag or branch you want to use in Repo2

      - name: Use Repository 2 Action
        uses: MonikaSinghal-22/Repo2-action-test@v1.3  # Replace 'author/repository2' with your GitHub repo path
        with:
          input-data: '{"user": "monika", "data": "12345"}'