name: Trigger Repository 2 Action

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Repository Name'
        required: true
        default: ''
      version:
        description: 'Version'
        required: true
        default: '0.0.0'
      checksum_data:
        description: 'Checksum data (in array format)'
        required: false
        default: '[]'

  # push:
  #   branches:
  #     - master  # Runs when code is pushed to 'main'

jobs:
  send-input:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "REPO_NAME=${{ github.repository }}"

      - name: Generate Input JSON
        run: |
            echo '{"user": "monika", "data": "12345"}' > input.json

    #   - name: Checkout Repository 2
    #     uses: actions/checkout@v4
    #     with:
    #         repository: MonikaSinghal-22/Repo2-action-test  # Repo2's name
    #         ref: v1.5  # The specific tag or branch you want to use in Repo2

      - name: List files for debugging
        run: |
            echo "Listing files in the current directory:"
            ls -R  # List all files recursively to see the directory structure
        shell: bash

      - name: Use Repository 2 Action
        uses: MonikaSinghal-22/Repo2-action-test@v1.10  # Replace 'author/repository2' with your GitHub repo path
        with:
          repository_name: ${{ github.event.repository_name}}
          version: ${{ github.event.version }}
          input-data: input.json