name: Trigger Repository 2

on:
  push:
    branches:
      - master  # Adjust as needed

jobs:
  send-input:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Input JSON
        run: |
          echo '{"user": "monika", "data": "12345"}' > input.json

      - name: Upload Input Artifact
        uses: actions/upload-artifact@v4
        with:
          name: input-data
          path: input.json
          